# Homework 4


Before you run your homework run the code below:

In [1]:
import os
import sys
import hashlib
import pandas as pd
import numpy as np
from urllib.request import urlopen
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.cluster import AgglomerativeClustering
import glob
import re
from collections import Counter
assert os.path.exists('../homeworks/HW4.ipynb')

info = sys.platform + '\n' + sys.version + '\n' + os.getcwd() + '\n' + os.getlogin()
name = hashlib.sha256(info.encode('utf-8')).hexdigest()
with open('../other/hw-4-'+name,'w') as f:
    f.write(info)

In [2]:
with open('../other/hw-4-'+name,'r') as f:
    info = f.read()
name = hashlib.sha256(info.encode('utf-8')).hexdigest()
assert os.path.exists('../other/hw-4-'+name)

## Task

Apply all of the supervised and unsupervised classification and clustering algorithms we learned so far for the [sonar dataset from UCI](http://archive.ics.uci.edu/ml/datasets/connectionist+bench+(sonar,+mines+vs.+rocks)).

The code for downloading the data is below. Don't load the data again and again in each subtask, refer the data as `SONAR` after you run the cell below.

In [3]:
with urlopen("https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/connectionist-bench/sonar/sonar.all-data") as fil:
    SONAR = pd.read_csv(fil, delimiter=',', header=None)


In [4]:
SONAR = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/connectionist-bench/sonar/sonar.all-data",sep=",",header=None)
SONAR.head(10)

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
5  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
6  0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083   
7  0.0519  0.0548  0.0842  0.0319  0.1158  0.0922  0.1027  0.0613  0.1465   
8  0.0223  0.0375  0.0484  0.0475  0.0647  0.0591  0.0753  0.0098  0.0684   
9  0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962   

       9  ...      51      52      53      54      55      56      57      58  \
0  0.2111 ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  0.0090   
1  0.2872 ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049  0.0052   
2  0.6194 ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164  0.0095   
3  0.1264 ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044  0.0040   
4  0.4459 ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048  0.0107   
5  0.3039 ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027  0.0051   
6  0.3513 ...  0.0201  0.0248  0.0131  0.0070  0.0138  0.0092  0.0143  0.0036   
7  0.2838 ...  0.0081  0.0120  0.0045  0.0121  0.0097  0.0085  0.0047  0.0048   
8  0.1487 ...  0.0145  0.0128  0.0145  0.0058  0.0049  0.0065  0.0093  0.0059   
9  0.0251 ...  0.0090  0.0223  0.0179  0.0084  0.0068  0.0032  0.0035  0.0056   

       59  60  
0  0.0032   R  
1  0.0044   R  
2  0.0078   R  
3  0.0117   R  
4  0.0094   R  
5  0.0062   R  
6  0.0103   R  
7  0.0053   R  
8  0.0022   R  
9  0.0040   R  

[10 rows x 61 columns]

Split the tasks into subtasks and into separate cells.  Also before your analysis for each subtask, write a short paragraph before explaining which algorithm you are going to use. Each subtask should look like this

## Subtask 1 : K- Means






In [5]:
# datayi %25 test datasi olacak sekilde boluyoruz
Xtrain, Xtest, Ytrain, Ytest = train_test_split(SONAR.iloc[:,0:60], SONAR.iloc[:,60], test_size=0.25)
model = KMeans(n_clusters=2, random_state=0)
# model should be fit with train data
model.fit(Xtrain)
# predict with test data
predicted = model.predict(Xtest)
labels = {"R":1, "M":0}
# accuracy sonucu asagidaki durumda daha kotu bunun sebebi label'lari yanlis tahmin etmis olmamiz
# labels = {"R":0, "M":1}
real = Ytest.map(lambda x: labels[x])
accuracy = accuracy_score(real,predicted)
print(confusion_matrix(real,predicted))


print(accuracy)

[[13 11]
 [15 13]]
0.5


## Subtask 2 : K-NN

Some explanation as to what you are going to do.

In [6]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(Xtrain,Ytrain)
predicted = model.predict(Xtest)
cm = confusion_matrix(Ytest,predicted)
print(cm)
accuracy = accuracy_score(Ytest,predicted)
print(accuracy)

[[22  2]
 [11 17]]
0.75


## Subtask 3 : Naive Bayes Classifier

Some explanation as to what you are going to do.

In [7]:
from sklearn.naive_bayes import GaussianNB

# create naive bayes classifier
gaunb = GaussianNB()

# train classifier with dataset
gaunb = gaunb.fit(Xtrain, Ytrain)

# predict using classifier
predicted = gaunb.predict(Xtest)

cm = confusion_matrix(Ytest,predicted)
print(cm)
accuracy = accuracy_score(Ytest,predicted)
print(accuracy)

[[12 12]
 [ 3 25]]
0.7115384615384616


## Subtask 4 : Linear Regression

Some explanation as to what you are going to do.

In [ ]:
# Train the model using the training sets
# Ytrain2 = Ytrain.replace(to_replace=['M', 'R'], value=[0, 1])
# Ytest2 = Ytest.replace(to_replace=['M', 'R'], value=[0, 1])
# model.fit(Xtrain, Ytrain)

# Make predictions using the testing set
# predicted = model.predict(Ytest)
# print(predicted)
# cm = confusion_matrix(Ytest,predicted)
# print(cm)
# accuracy = accuracy_score(Ytest,predicted)
# print(accuracy)
# ValueError: could not convert string to float: 'M'

## Subtask 5 : Hiearchical clustering

Some explanation as to what you are going to do.

In [ ]:
cluster = AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')  
cluster.fit_predict(X)  

## Subtask 6 : Logistic regression

Some explanation as to what you are going to do.